run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/Abhishek2095/kv-stash
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  funlen:
    lines: 80
    statements: 40
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  nakedret:
    max-func-lines: 30

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - gocyclo
    - goconst
    - misspell
    - lll
    - nakedret
    - funlen

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - gocyclo
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
