# Pre-commit hooks configuration
# Install with: pre-commit install
repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: make
        args: [lint-docker]
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-fmt
        name: go-fmt
        entry: gofmt
        args: [-l, -s]
        language: system
        files: \.go$
        fail_fast: true

      - id: go-vet
        name: go-vet
        entry: go
        args: [vet, ./...]
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-test
        name: go-test
        entry: go
        args: [test, -v, ./...]
        language: system
        files: \.go$
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
